// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as dotenvConfig } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (Vercel's `vercel env pull` writes here), then .env as
// a fallback. CI / Vercel runtime injects env vars directly so both calls are no-ops.
dotenvConfig({ path: ".env.local" });
dotenvConfig();

// Prisma 7 reads the datasource URL from this config rather than from `env()`
// in schema.prisma. We prefer DIRECT_URL for migration/CLI work (the Vercel
// Postgres non-pooled URL) and fall back to the pooled DATABASE_URL.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"] ?? "",
  },
});
