"use client";

import { Code2, Sparkles } from "lucide-react";
import { MockupBanner, Section, Stat, Tag, AIInsight, PageStack } from "../../_components/PillarCommsUI";
import { TOKENS_LIBRARY } from "../../_data/extendedData";

export default function PersonalisationPage() {
  const grouped = {
    static: TOKENS_LIBRARY.filter((t) => t.type === "static"),
    dynamic: TOKENS_LIBRARY.filter((t) => t.type === "dynamic"),
    ai: TOKENS_LIBRARY.filter((t) => t.type === "ai"),
  };
  return (
    <div className="page animate-in">
      <MockupBanner />
      <div style={{ marginBottom: 24 }}>
        <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.12em", color: "#8b5cf6", marginBottom: 8 }}>AI Layer · Personalisation</div>
        <h1 className="page-title gradient-text" style={{ fontSize: 30, margin: 0, background: "linear-gradient(135deg, #8b5cf6, #6366f1)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>
          Personalisation tokens
        </h1>
        <p className="page-desc" style={{ margin: "8px 0 0", maxWidth: 720 }}>Static, dynamic and AI-generated merge tokens - the language of one-to-one comms at scale.</p>
      </div>
      <PageStack>
        <div className="stat-card-grid">
          <Stat label="Tokens defined" value={TOKENS_LIBRARY.length.toString()} icon={<Code2 className="h-4 w-4" />} />
          <Stat label="AI tokens" value={grouped.ai.length.toString()} hint="LLM-generated per send" />
          <Stat label="Render fail rate" value="0.04%" hint="last 30 days" />
          <Stat label="Avg lift vs no-tokens" value="+38%" hint="open rate" />
        </div>
        <AIInsight title="AI tokens are your highest-leverage personalisation surface" tone="indigo">
          The <code>ai_personal_intro</code> token (currently used in 14,820 sends) lifts open rate by +28% and reply rate by +44% vs static intros. Cost: ~£0.002 per render. ROI: ~140×. <strong>Recommendation: enable on the recurring-failure cadence.</strong>
        </AIInsight>
        {(["static", "dynamic", "ai"] as const).map((g) => (
          <Section key={g} title={`${g === "static" ? "Static" : g === "dynamic" ? "Dynamic (computed)" : "AI-generated"} tokens`} subtitle={g === "static" ? "Pulled directly from CRM record" : g === "dynamic" ? "Calculated at send-time from rules" : "Generated by LLM at send-time"}>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 2fr auto", gap: 10, fontSize: 12, alignItems: "center" }}>
              <div style={{ fontSize: 10, fontWeight: 700, color: "var(--text-3)", textTransform: "uppercase" }}>Token</div>
              <div style={{ fontSize: 10, fontWeight: 700, color: "var(--text-3)", textTransform: "uppercase" }}>Example render</div>
              <div style={{ fontSize: 10, fontWeight: 700, color: "var(--text-3)", textTransform: "uppercase" }}>Uses</div>
              {grouped[g].map((t) => (
                <Tok key={t.name} name={t.name} ex={t.example} uses={t.uses} ai={g === "ai"} />
              ))}
            </div>
          </Section>
        ))}
        <div style={{ display: "flex", gap: 8, alignItems: "center" }}><Tag label="Mockup" /></div>
      </PageStack>
    </div>
  );
}

function Tok({ name, ex, uses, ai }: { name: string; ex: string; uses: number; ai: boolean }) {
  return (
    <>
      <code style={{ background: ai ? "rgb(139 92 246 / 0.10)" : "rgb(99 102 241 / 0.08)", color: ai ? "#8b5cf6" : "#6366f1", padding: "3px 7px", borderRadius: 4, fontSize: 11, fontWeight: 700 }}>
        {ai && <Sparkles className="h-3 w-3 inline" style={{ marginRight: 3 }} />}
        {`{${name}}`}
      </code>
      <span style={{ color: "var(--text-2)", fontStyle: "italic" }}>{ex}</span>
      <span style={{ fontVariantNumeric: "tabular-nums", color: "var(--text-3)", textAlign: "right" }}>{uses.toLocaleString()}</span>
    </>
  );
}
